# permissions for end users to edit hsses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hss-editor-role
rules:
- apiGroups:
  - demo.example.com
  resources:
  - hsses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.example.com
  resources:
  - hsses/status
  verbs:
  - get
