---
apiVersion: v1
kind: Service
metadata:
  name: hss
spec:
  ports:
  - name: s6a
    port: 3868
    protocol: TCP
  - name: config-port
    port: 8080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hss-headless
spec:
  clusterIP: None
  ports:
  - name: s6a
    port: 3868
    protocol: TCP
  - name: config-port
    port: 8081
    protocol: TCP

